### PR TITLE
fix issue of section title format

### PR DESCRIPTION
**Pull request by lifematrix**

### CODE REVIEW

**Comment by citypw** [comment]
Hey  lifematrix , could u plz pull the latest repo and file a pull request again? I saw there's a conflict.

**Comment by lifematrix** [comment]
Hi, I have created a pull request again.

**Comment by lifematrix** [comment]
Hi, I have pull upstream branch & merge it. I submit a new  pull request.

**Comment by lifematrix** [comment]
Great, format of section title is correct now.

**Pull request merged**
